// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-json-imports.ts



export interface DesignSystemFile {
  name: string;
  type: 'components' | 'styles';
  data: any;
}

export const jsonDataFiles: DesignSystemFile[] = [

];
